"""otp

Revision ID: 224ef692d5ec
Revises: f308242f8af2
Create Date: 2023-06-03 14:16:43.429054

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '224ef692d5ec'
down_revision = 'f308242f8af2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('emailverificationcode',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_emailverificationcode_id'), 'emailverificationcode', ['id'], unique=False)
    op.create_table('telverificationcode',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tel', sa.String(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_telverificationcode_id'), 'telverificationcode', ['id'], unique=False)
    op.alter_column('user', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_index(op.f('ix_telverificationcode_id'), table_name='telverificationcode')
    op.drop_table('telverificationcode')
    op.drop_index(op.f('ix_emailverificationcode_id'), table_name='emailverificationcode')
    op.drop_table('emailverificationcode')
    # ### end Alembic commands ###
