"""ip address

Revision ID: 5bc518c7b33b
Revises: 8db36ad8d0f2
Create Date: 2023-06-12 17:42:49.286970

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5bc518c7b33b'
down_revision = '8db36ad8d0f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('authsession', sa.Column('ip_address', sa.String(), nullable=True))
    op.drop_column('authsession', 'host')
    op.drop_column('authsession', 'real_ip')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('authsession', sa.Column('real_ip', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('authsession', sa.Column('host', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('authsession', 'ip_address')
    # ### end Alembic commands ###
