"""end session

Revision ID: a9724f45771b
Revises: e8b5e5ed20a3
Create Date: 2023-07-26 07:22:44.485598

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9724f45771b'
down_revision = 'e8b5e5ed20a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('authsession', sa.Column('ended', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('authsession', 'ended')
    # ### end Alembic commands ###
