"""user last activity

Revision ID: e8b5e5ed20a3
Revises: 5bc518c7b33b
Create Date: 2023-06-12 23:17:22.908198

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8b5e5ed20a3'
down_revision = '5bc518c7b33b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('last_activity', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_activity')
    # ### end Alembic commands ###
