"""tel field

Revision ID: f308242f8af2
Revises: 3db219f56ca7
Create Date: 2023-06-03 13:07:29.264354

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f308242f8af2'
down_revision = '3db219f56ca7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('tel', sa.String(), nullable=True))
    op.alter_column('user', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_index(op.f('ix_user_tel'), 'user', ['tel'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_tel'), table_name='user')
    op.alter_column('user', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('user', 'tel')
    # ### end Alembic commands ###
